### PR TITLE
Initial changes to the benchmark suite

### PR DESCRIPTION
**Pull request by skrzypo987**
Refer to readme and commit messages for additional info

### CODE REVIEW

**Review by jvanzyl — COMMENTED** [review]
Is there a way to optionally turn these on? We do get requests for JREs with features like CRAC turned on.

**Review by jvanzyl — APPROVED** [review]

**Review by pnasrat — CHANGES_REQUESTED** [review]
Can we `.gitignore` the results themselves so we can later move to  something external eg cloud storage to publish to them to.

**Comment by pnasrat** [comment]
@jvanzyl we can use the pubsub events to trigger it for releases, I discussed that with @skrzypo987 

@skrzypo987 oh ignore my commment on results that will go away when I squash and merge

**Comment by skrzypo987** [comment]
> Is there a way to optionally turn these on? We do get requests for JREs with features like CRAC turned on.

At this point, the suite contents are controlled by maven profiles. I don't now how elastic those are, but if not enough, some basic annotation based system should be easily doable.

**Pull request merged**
